import React from "react";
import "./globals.css";
import { Provider } from "./utils/provider";

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<Provider>
			<html lang="en">
				<body>{children}</body>
			</html>
		</Provider>
	);
}
